name: Pull Request
on: [pull_request]

jobs:
  blocker:
    name: Close pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull@v2.0.1
        with:
         comment: |
           We don't accept Pull Requests.
         delete-branch: true
